version: '3.4'

x-common-config: &common_config
  image: squad/local
  build:
    context: .
  volumes:
    - home:/app
    - storage:/storage
  environment:
    - SQUAD_CELERY_BROKER_URL=amqp://rabbitmq
    - XDG_DATA_HOME=/app

volumes:
  home:
  storage:

services:
  rabbitmq:
    image: rabbitmq

  dbmigrate:
    <<: *common_config
    command: squad-admin migrate
    deploy:
      restart_policy:
        condition: none

  web:
    <<: *common_config
    command: squad --fast --bind 0.0.0.0:5000
    ports:
      - '5000:5000'

  worker:
    <<: *common_config
    command: squad-worker

  listener:
    <<: *common_config
    command: squad-listener

  scheduler:
    <<: *common_config
    command: squad-scheduler
